PR: FEAT) Gym CRUD입니다.
sparta-final/final-project pull request #22
Opened 2023-03-03 12:26 UTC by Hojunz

체육관 CRUD 완성본 입니다.  혹시라도 아직 부족한 기능 있으면 말씀해주세요~

2023-03-03 12:37 UTC, kingseungil requested changes
수정바람!

2023-03-03 12:37 UTC, kingseungil commented on src/domain/gym/gym.controller.ts
> +
전체 운동시설 가져오는 api도 필요할것같아용

2023-03-03 12:37 UTC, kingseungil commented on src/domain/gym/gym.service.ts
> +    console.log('이거', file.certification[0].location);
콘솔 지우셔야합니다!

2023-03-03 12:37 UTC, kingseungil commented on src/domain/gym/gym.service.ts
> +    return deletegym;
delete한거 리턴해주는 이유는?

2023-03-03 12:45 UTC, HxxJ-project commented on src/domain/gym/gym.service.ts
> +    console.log('이거', file.certification[0].location);
console.log 지워주세욥

2023-03-03 12:47 UTC, HxxJ-project approved these changes

2023-03-04 08:59 UTC, HxxJ-project commented on src/domain/gym/gym.service.ts
> +    await this.gymsrepository.update(gymId, {
update시 이미지 업로드가 문제될 수도 있으니 트랜잭션으로 쓰시는게 어떠실까요?

2023-03-05 00:15 UTC, kingseungil approved these changes
굳 좋습니다~

2023-03-05 01:55 UTC, merged